### ISSUE TITLE
Need better webpage for searches with no rows

### ISSUE THREAD

**Issue by stephenlienharrell** [TACC/tacc_stats#21]
Currently we just get an exception if there are no rows on a search, this needs to be an actual page, where the user can search again, it might be nice to stay on the same page if there are no rows via javascript.

**Comment by stephenlienharrell** [comment]
Additionally, when entering a username in LS6 stats that either has no job history or that doesn’t exist, it’s not returning the Requested search failed. like usual, it’s redirecting to DataNotFoundException at /machine/search/ error page. This should return an error page that is helpful and identifies the correct missing data.

**Comment by nicejunjie** [comment]
fixed in commit 301ed9f, and alive on ls6.
